workflows:
  android-build:
    name: ACAP Android
    instance_type: mac_mini_m2
    working_directory: acap_app
    environment:
      flutter: stable
    scripts:
      - name: Switch Flutter version
        script: |
          cd /Users/builder/programs/flutter
          git fetch --tags
          git checkout 3.22.3
          flutter pub cache repair || true
      - name: Get packages
        script: /Users/builder/programs/flutter/bin/flutter pub get
      - name: Build APK
        script: /Users/builder/programs/flutter/bin/flutter build apk --debug
    artifacts:
      - acap_app/build/app/outputs/flutter-apk/app-debug.apk
