workflows:
  android-build:
    name: ACAP Android
    instance_type: mac_mini_m2
    working_directory: acap_app
    environment:
      flutter: stable
    scripts:
      - name: Switch Flutter version
        script: |
          cd /Users/builder/programs/flutter
          git fetch --tags
          git checkout 3.22.3
          rm -f bin/cache/flutter_tools.snapshot
          rm -f bin/cache/flutter_tools.stamp
          export PATH="/Users/builder/programs/flutter/bin:$PATH"
          flutter --version
      - name: Get packages
        script: |
          export PATH="/Users/builder/programs/flutter/bin:$PATH"
          flutter pub get
      - name: Build APK
        script: |
          export PATH="/Users/builder/programs/flutter/bin:$PATH"
          echo "flutter.sdk=/Users/builder/programs/flutter" > android/local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties
          cd android && ./gradlew assembleDebug
    artifacts:
      - acap_app/build/app/outputs/flutter-apk/app-debug.apk
